apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: solidarity
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: solidarity-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: solidarity-secrets
                  key: POSTGRES_PASSWORD


            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: solidarity-secrets
                  key: POSTGRES_DB

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
          resources: 
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

        - name: init-sql
          configMap:
            name: postgres-init-sql