--
-- PostgreSQL database dump
--

\restrict 71vLCM2YFruG6b3a14HUCaYxL6QEiEoLoMtjDQWabmJTDJN7GxsFIm3hNeRUO4V

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: associations; Type: TABLE; Schema: public; Owner: ness
--

CREATE TABLE public.associations (
    id bigint NOT NULL,
    city character varying(255) NOT NULL,
    contact character varying(255),
    description character varying(255),
    link character varying(255),
    name character varying(255),
    tag character varying(255),
    CONSTRAINT associations_tag_check CHECK (((tag)::text = ANY ((ARRAY['FOOD'::character varying, 'SHELTER'::character varying, 'HYGIENE'::character varying, 'HEALTHCARE'::character varying, 'EDUCATION'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.associations OWNER TO ness;

--
-- Name: associations_id_seq; Type: SEQUENCE; Schema: public; Owner: ness
--

ALTER TABLE public.associations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.associations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: infos; Type: TABLE; Schema: public; Owner: ness
--

CREATE TABLE public.infos (
    id bigint NOT NULL,
    content text NOT NULL,
    link character varying(255),
    title character varying(255) NOT NULL
);


ALTER TABLE public.infos OWNER TO ness;

--
-- Name: infos_id_seq; Type: SEQUENCE; Schema: public; Owner: ness
--

ALTER TABLE public.infos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.infos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: ness
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    user_name character varying(255)
);


ALTER TABLE public.users OWNER TO ness;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: ness
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: associations; Type: TABLE DATA; Schema: public; Owner: ness
--

COPY public.associations (id, city, contact, description, link, name, tag) FROM stdin;
1	Marseille	contact@medecinsdumonde.org	Provides medical care to vulnerable populations in France and abroad, focusing on health access for those in precarious situations.	https://www.medecinsdumonde.org	Médecins du Monde	HEALTHCARE
3	Paris	info@restosducoeur.org	A French charity that distributes food packages and hot meals to people in need and helps with housing support and social inclusion.	https://www.restosducoeur.org	Restos du Cœur	FOOD
4	Paris	contact@fap.fr	Works to fight housing exclusion and homelessness in France, providing support and advocacy for vulnerable populations.	https://www.fondation-abbe-pierre.fr	Fondation Abbé Pierre	SHELTER
5	Paris	contact@samusocial.paris	Emergency outreach service helping homeless people in Paris, providing medical care, food, and temporary shelter.	https://www.samusocial.paris	Samu Social de Paris	HEALTHCARE
6	Bordeaux	contact@emmaus-france.org	Provides shelter, social support, and reintegration programs for homeless and disadvantaged people across France.	https://emmaus-france.org	Emmaüs	SHELTER
7	Marseille	contact@lerelais.org	Provides hygiene products, laundry services, and sanitary support to homeless and vulnerable populations in France.	https://www.lerelais.org	Le Relais – Hygiene Aid	HYGIENE
\.


--
-- Data for Name: infos; Type: TABLE DATA; Schema: public; Owner: ness
--

COPY public.infos (id, content, link, title) FROM stdin;
2	Locate local food banks and meals for homeless people.	https://www.restosducoeur.org/en	Food Bank Assistance
3	Hospital-based clinics (Permanences d'Accès aux Soins de Santé) where you can see a doctor and get medicine for free without insurance.	https://www.sante.gouv.fr/soins-et-maladies/prises-en-charge-specialisees/pass	PASS (Free Healthcare)
4	A legal recourse for homeless or poorly housed people to be recognized as high-priority for social housing by the State.	https://www.service-public.fr/particuliers/vosdroits/F18005	Right to Housing (DALO)
5	Registering for a legal address (domiciliation) is mandatory to access social benefits (RSA), vote, or open a bank account.	https://www.service-public.fr/particuliers/vosdroits/F17359	Administrative Address (CCAS)
6	Free access to showers and restrooms in municipal centers (bains-douches) or day shelters.	https://soliguide.fr/en/search?categories=hygiene	Hygiene & Public Showers
7	Safe places to store bags and personal belongings during the day so you can attend appointments freely.	https://www.paris.fr/pages/les-bagageries-solidaires-3521	Solidarity Luggage Storage
8	Free 24/7 emergency number to request a bed in a shelter or to report someone in distress in the street.	tel:115	115 - Emergency Housing
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: ness
--

COPY public.users (id, email, password, user_name) FROM stdin;
1	megumi@example.com	$2a$10$Sjbnzw/mpPhYIG61LnvVkeusH3LIhVaX8nr0ONZcfTtMZIAW09xsu	megumi
2	nishinoya@example.com	$2a$10$cs1mdYGCY/naR71pdTYHyuvPx2RgbxmKQuJyKV4IZwKfQcVc/Skaa	nishinoya
\.


--
-- Name: associations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ness
--

SELECT pg_catalog.setval('public.associations_id_seq', 7, true);


--
-- Name: infos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ness
--

SELECT pg_catalog.setval('public.infos_id_seq', 8, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ness
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: associations associations_pkey; Type: CONSTRAINT; Schema: public; Owner: ness
--

ALTER TABLE ONLY public.associations
    ADD CONSTRAINT associations_pkey PRIMARY KEY (id);


--
-- Name: infos infos_pkey; Type: CONSTRAINT; Schema: public; Owner: ness
--

ALTER TABLE ONLY public.infos
    ADD CONSTRAINT infos_pkey PRIMARY KEY (id);


--
-- Name: users ukk8d0f2n7n88w1a16yhua64onx; Type: CONSTRAINT; Schema: public; Owner: ness
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukk8d0f2n7n88w1a16yhua64onx UNIQUE (user_name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: ness
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict 71vLCM2YFruG6b3a14HUCaYxL6QEiEoLoMtjDQWabmJTDJN7GxsFIm3hNeRUO4V

